import pickle
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

CLIM = ROOT / "models" / "climatology_provinces.pkl"


def _load_clim():
    if not CLIM.exists():
        pytest.skip("ยังไม่มี climatology_provinces.pkl — รัน freeze ก่อน")
    # pickle is safe: file is generated by freeze_provinces_climatology.py from
    # trusted local sources only — never loaded from external/untrusted input.
    with open(CLIM, "rb") as fh:
        return pickle.load(fh)


def test_frozen_climatology_structure():
    art = _load_clim()
    assert set(art["thr90_grid"].dims) == {"dayofyear", "latitude", "longitude"}
    assert art["thr90_grid"].sizes["dayofyear"] == 366
    assert art["n_provinces"] == 77
    assert art["leads"] == [2, 3, 4, 5, 6]


def test_base_rate_per_province_in_range_and_varies():
    art = _load_clim()
    base = art["base_rate"]
    assert len(base) == 77
    vals_lead2 = [base[p][2] for p in base]
    for v in vals_lead2:
        assert 0.0 <= v <= 1.0
    # per-province ต้อง "ต่างกันจริง" (แก้ quirk pooled ที่ทุกจังหวัดเท่ากัน)
    assert len(set(round(v, 4) for v in vals_lead2)) > 1
